version: '3'

services:
  redis:
    image: redis

  db:
    image: postgres:10

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
